[project]
name = "rag-allaboutberlin"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.33.0",
    "beautifulsoup4==4.12.3",
    "lxml>=6.1.0",
    "minsearch",
    "openai",
    "jupyter",
    "python-dotenv",
    "sentence-transformers>=5.5.1",
    "toyaikit>=0.0.11",
    "tqdm>=4.67.3",
    "pandas>=3.0.3",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov==6.0.0",
    "responses==0.25.3",
]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "--cov=scraper --cov-report=term-missing --cov-fail-under=80"
